/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import MultiPlay from "./script/MultiPlay"
import SinglePlay from "./script/SinglePlay"
import Index from "./script/Index"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/MultiPlay.js",MultiPlay);
		reg("script/SinglePlay.js",SinglePlay);
		reg("script/Index.js",Index);
    }
}
GameConfig.width = 720;
GameConfig.height = 1280;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Main/Index.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
